export const types = {
    SET_LOADING: 'SET_LOADING',
    RESET_LOADING: 'RESET_LOADING',
    SET_LIST: 'SET_LIST',
    SET_HOVERED: 'SET_HOVERED',
    RESET_HOVERED: 'RESET_HOVERED',
    SET_ORDERING: 'SET_ORDERING'
}